export const homeObjOne = {
  id: "history",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "History",
  headLine: "How did Lambda Phi Epsilon start?",
  description:
    "Lambda Phi Epsilon was formed on February 25, 1981 at the University of California, Los Angeles. Noting that Asian fraternities and sororities at the University of California campuses were recognized only as service organizations due to their membership's focus on specific Asian groups and exclusion of other ethnic groups, the founders aimed to create a fraternity that transcends the traditional boundaries of national origins, bridges the gaps between those communities, and is recognized by the Greek community at large. While the original charter focused on Asian Pacific Americans, people from all ethnic backgrounds were welcome to join.",
  buttonLabel: "Learn More",
  imgStart: false,
  img: require("../../images/founders.png"),
  img2: require("../../images/founders2.jpg"),
  alt: "Founders",
  dark: true,
  primary: true,
  darkText: false,
  location: "/history",
};
export const homeObjTwo = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "About Us",
  headLine: "How was the FSU Associate Chapter founded? ",
  description:
    "In the spring semester of 2004 at the Florida State University, a group of six strong men formed the interest group, 'APEX: Florida State Asian Greek Interest Group' which would one day become Lambda Phi Epsilon. Under the guidance of Phillip 'Tonka' Ha, the international chairman at the time, principle founder David Huang brought together a group of men who were seeking for a way to enhance their college experience and grow as leaders among men. David was soon joined by Jimmy Chen, Alex Choi, Rigel Trajano, Craig Puntel, Can Hu, and James Dungca. As APEX, they were set on getting established on campus as a group dedicated to Asian awareness, leadership, and brotherhood. Through socials, philanthropy events, and support from other organizations, APEX was able to build a good reputation as an outstanding organization. Along the way, Sohail Khamesi, Eric Yang, Rashan Young, Ti Dinh, Daniel Jeon, and Mike Chen joined the interest group. It was the summer of 2005 when Lambda Phi Epsilon allowed for APEX to initiate the educational process to become leaders among men.  Under their principle hosts Sho Takahashi and Hy Huynh from the University of California, Santa Barbara, and from the California Polytechnic State University, San Luis Obispo, respectfully, these thirteen men were on their way to become Lambdas at the Florida State University. On January 2nd, 2006, they had crossed into the eternal brotherhood of Lambda Phi Epsilon. Although the chapter would come to build a significant reputation in the community, several classes later it remained unrecognized by the Florida State University. The brothers during the time decided that a large sacrifice would need to be made for the chapter to achieve its collective ambitions. They would choose to discontinue the chapter, creating a new void for the future generation of Lambda Phi Epsilon to recharter, fully recognized by the university.The time came in the Fall of 2018 when the recharter class founder, Byron Solis, brought together seven men with the potential to be leaders in their respective communities.In March, these men, Michael Ko, Kyle Lu, Alexander No, Joshua Pangusan, Alexander Palaganas, Byron Solis, David Uy, and Austyn Vong, crossed to become the Recharter Zeta class here at the Florida State University.",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/fsu_founders.png"),
  img2: require("../../images/fsu_founders.png"),
  alt: "Founders",
  dark: false,
  primary: false,
  darkText: true,
  location: "/aboutus",
};
export const homeObjThree = {
  id: "philanthropy",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Philanthropy",
  headLine: "What is Lambda Phi Epsilon's philanthropy?",
  description:
    "The fraternity's national philanthropy works to raise awareness for bone marrow drives. For patients with leukemia or any other blood disorder, the best chance of finding a matching donor lies within their own ethnic community. Asian donors comprise a small fraction (7% as of January 2013) of the National Marrow Donor Program (NMDP). Because of this, every chapter of Lambda Phi Epsilon hosts several bone marrow drives in conjunction with organizations like the Asian American Donor Program, Asians for Miracle Marrow Matches, and the former Cammy Lee Leukemia Foundation to inform, educate, and recruit potential marrow donors for the NMDP. Lambda Phi Epsilon recognized bone marrow drives as the national philanthropy when Evan Chen, a member from Stanford University, was diagnosed with leukemia in 1995. The fraternity organized a campus-wide movement to find a bone marrow match for Chen. What resulted was the largest bone marrow typing drive in the history of the NMDP and AADP (Asian American Donor Program). In a matter of days, over 2,000 people were typed. A match was eventually found for Chen, but by that time, the cancer had taken its toll and he died 1996. Since then, the fraternity organizes annual bone marrow drives to help others find matching donors. Collectively, chapters of Lambda Phi Epsilon amass hundreds of new registrants every year in national campaigns like Save Janet Liang and Save Nina Louie.",
  buttonLabel: "Learn More",
  imgStart: false,
  img: require("../../images/bethematch.jpg"),
  img2: require("../../images/bethematch.jpg"),
  alt: "Founders",
  dark: true,
  primary: true,
  darkText: false,
  location: "/philanthropy",
};
