export const homeObjOne = {
  id: "history",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "History",
  headLine: "How did Lambda Phi Epsilon start?",
  description:
    "Lambda Phi Epsilon was formed on February 25, 1981 at the University of California, Los Angeles. Noting that Asian fraternities and sororities at the University of California campuses were recognized only as service organizations due to their membership's focus on specific Asian groups and exclusion of other ethnic groups, the founders aimed to create a fraternity that transcends the traditional boundaries of national origins, bridges the gaps between those communities, and is recognized by the Greek community at large. While the original charter focused on Asian Pacific Americans, people from all ethnic backgrounds were welcome to join.",
  buttonLabel: "Learn More",
  imgStart: false,
  img: require("../../images/founders.png"),
  alt: "Founders",
  dark: true,
  primary: true,
  darkText: false,
  location: "history",
};
export const homeObjTwo = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "About Us",
  headLine: "How was the FSU Associate Chapter founded? ",
  description:
    "In the spring semester of 2004 at the Florida State University, a group of six strong men formed the interest group, 'APEX: Florida State Asian Greek Interest Group' which would one day become Lambda Phi Epsilon. Under the guidance of Phillip 'Tonka' Ha, the international chairman at the time, principle founder David Huang brought together a group of men who were seeking for a way to enhance their college experience and grow as leaders among men. David was soon joined by Jimmy Chen, Alex Choi, Rigel Trajano, Craig Puntel, Can Hu, and James Dungca.",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/fsu_founders.png"),
  alt: "Founders",
  dark: false,
  primary: false,
  darkText: true,
  location: "aboutus",
};
export const homeObjThree = {
  id: "philanthropy",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Philanthropy",
  headLine: "What is Lambda Phi Epsilon's philanthropy?",
  description:
    "The fraternity's national philanthropy works to raise awareness for bone marrow drives. For patients with leukemia or any other blood disorder, the best chance of finding a matching donor lies within their own ethnic community. Asian donors comprise a small fraction (7% as of January 2013) of the National Marrow Donor Program (NMDP). Because of this, every chapter of Lambda Phi Epsilon hosts several bone marrow drives in conjunction with organizations like the Asian American Donor Program, Asians for Miracle Marrow Matches, and the former Cammy Lee Leukemia Foundation to inform, educate, and recruit potential marrow donors for the NMDP.",
  buttonLabel: "Learn More",
  imgStart: false,
  img: require("../../images/bethematch.jpg"),
  alt: "Founders",
  dark: true,
  primary: true,
  darkText: false,
  location: "philanthropy",
};
